### ISSUE TITLE
Update systems in readme to modern ones?

### ISSUE THREAD

**Issue by micwoj92** [danamlund/sensors-lxpanel-plugin#8]
It might look like the software is obsolete when it mentions ubuntu 11.04

**Comment by danamlund** [comment]
Excellent idea. I added an installation guide for Ubuntu 20.04, and updated some install scripts to align better with ubuntu 20.04.
It was more work than expected downloading a distro and installing in vm and setting up lxde and then seeing how to install the sensors plugin. So I hope its enough with installation instructions for just ubuntu.

**Comment by micwoj92** [comment]
Thanks man. Also the links to Funtoo/Gentoo and Fedora seem to be dead :/

**Comment by danamlund** [comment]
I could not find any archived versions of the dead links. So I removed them from the README.
